### ISSUE TITLE
`caniusepython3` don't see taxjar library

### ISSUE THREAD

**Issue by wowkin2** [taxjar/taxjar-python#15]
Here is what I see in console output.
```
>>> caniusepython3 -r requirements.txt

Finding and checking dependencies ...
[ERROR] Failed to get external data for https://www.red-dove.com/pypi/projects/T/taxjar/project.json: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "~/venv3/lib/python3.6/site-packages/distlib/util.py", line 913, in _get_external_data
    resp = urlopen(url)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[WARNING] taxjar not found
```

I know, that in documentation you shown that python 3+ is supporting but still this may help.

**Comment by ScottRudiger** [comment]
Thanks for reporting the issue @wowkin2. We'll get this on our backlog and fix it soon. 👍
